#Application configuration
notified:
  #Thread pool size. Used for parallel message sending
  thread-pool-size: 2

#Email transports configuration
transports: []

#Notification templates
templates: []
